name: Build Documentation

on:
  push: 
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: 
      - opened
      - synchronize


jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python and Pip
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MKDocs with plugins
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            mkdocs-material
            mkdocs-git-revision-date-plugin

      - name: Run 'mkdocs build'
        run: mkdocs build
